# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group <https://www.opalmedapps.com>
#
# SPDX-License-Identifier: MIT

# to test the docker-build workflow in the test workflow
FROM alpine:latest

RUN apk add --no-cache bash
